var N = null;var sourcesIndex = {};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["cfg_if"] = {"name":"","files":["lib.rs"]};
sourcesIndex["dev_menu"] = {"name":"","files":["lib.rs","menu.rs","menu_item.rs"]};
sourcesIndex["draw_state"] = {"name":"","files":["lib.rs","preset.rs","state.rs","target.rs"]};
sourcesIndex["float"] = {"name":"","files":["lib.rs"]};
sourcesIndex["freetype"] = {"name":"","files":["bitmap.rs","bitmap_glyph.rs","error.rs","face.rs","glyph.rs","glyph_slot.rs","lib.rs","library.rs","outline.rs","render_mode.rs","stroker.rs","tt_os2.rs","tt_postscript.rs"]};
sourcesIndex["freetype_sys"] = {"name":"","files":["lib.rs"]};
sourcesIndex["gfx"] = {"name":"","dirs":[{"name":"macros","files":["mod.rs","pso.rs","structure.rs"]},{"name":"pso","files":["buffer.rs","bundle.rs","mod.rs","resource.rs","target.rs"]}],"files":["encoder.rs","factory.rs","lib.rs","shade.rs","slice.rs"]};
sourcesIndex["gfx_core"] = {"name":"","files":["buffer.rs","command.rs","dummy.rs","factory.rs","format.rs","handle.rs","lib.rs","mapping.rs","memory.rs","pso.rs","shade.rs","texture.rs"]};
sourcesIndex["gfx_debug_draw"] = {"name":"","files":["debug_renderer.rs","lib.rs","line_renderer.rs","utils.rs"]};
sourcesIndex["gfx_text"] = {"name":"","files":["font.rs","lib.rs"]};
sourcesIndex["input"] = {"name":"","files":["after_render.rs","button.rs","close.rs","controller.rs","cursor.rs","event_id.rs","focus.rs","generic_event.rs","idle.rs","keyboard.rs","lib.rs","mouse.rs","render.rs","resize.rs","text.rs","touch.rs","update.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"linux_like","dirs":[{"name":"linux","dirs":[{"name":"gnu","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs","not_x32.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["log"] = {"name":"","files":["lib.rs","macros.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["serde"] = {"name":"","dirs":[{"name":"de","files":["ignored_any.rs","impls.rs","mod.rs","seed.rs","utf8.rs","value.rs"]},{"name":"private","files":["de.rs","doc.rs","mod.rs","ser.rs","size_hint.rs"]},{"name":"ser","files":["fmt.rs","impls.rs","impossible.rs","mod.rs"]}],"files":["integer128.rs","lib.rs","macros.rs"]};
sourcesIndex["serde_derive"] = {"name":"","dirs":[{"name":"internals","files":["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","receiver.rs","respan.rs","symbol.rs"]}],"files":["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","try.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
sourcesIndex["vecmath"] = {"name":"","files":["lib.rs","traits.rs"]};
sourcesIndex["viewport"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
